version: '3'

services:
  orcca-postgres:
    image: postgres:11
    container_name: 'orcca-postgres-container'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  postgres:
