version: '3'

services:
  postgres:
    image: postgres:11
    container_name: 'orcca_database_container'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=orcca
      - POSTGRES_PASSWORD=orcca
      - POSTGRES_DB=orcca_db

volumes:
  postgres:
